# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

wallet_routes:
    resource: routes/wallets.yaml

vending_machine_routes:
    resource: routes/vending_machine.yaml

test_routes:
    resource: routes/test.yaml
