# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Wallet\Domain\Repository\WalletRepositoryInterface:
        alias: App\Wallet\Infrastructure\Repository\DoctrineWalletRepository

    App\VendingMachine\Domain\Repository\VendingMachineRepositoryInterface:
        alias: App\VendingMachine\Infrastructure\Repository\DoctrineVendingMachineRepository

    App\Shared\Application\TransactionManagerInterface:
        alias: App\Shared\Infrastructure\Database\DbalTransactionManager

    App\:
        resource: '../src/'
